### ISSUE TITLE
32 bit support

### ISSUE THREAD

**Issue by migueldvb** [catharsis/spotifile#13]
Is there any chance to have support for i686 architecture?

**Comment by catharsis** [comment]
You know, I hadn't even considered it. But I can't see any obvious reason why that'd be unreasonable to expect. I'll give it a go during the weekend :-)

**Comment by catharsis** [comment]
@migueldvb 
i686 should now work, feel free to try it out for yourself by doing a build from the master branch.
`spotifile: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=92c100b8cfe23b3ff74be57aa2621ae840aab7af, not stripped`

**Comment by migueldvb** [comment]
Thank you, building spotifile on a 32bit computer works well. I get a warning from
`autoreconf -sif`

```
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.
configure.ac:4: installing './compile'
configure.ac:3: installing './missing'
```

but compilation is OK and all tests pass.

**Comment by catharsis** [comment]
No need to worry about that, it shows up on my system as well. But, I probably should fix it regardless... I'll create an issue.
