### ISSUE TITLE
Inconsistent ini header

### ISSUE THREAD

**Issue by chelmertz** [catharsis/spotifile#29]
Readme says "[spotifile]", syslog says "[spotify]", and also complains about
GError usage:

```
Sep 23 00:58:19 bubbis spotifile[19071]: No Spotify username specified: Key file does not have group 'spotify'
Sep 23 00:58:19 bubbis spotifile[19071]: GError set over the top of a previous GError or uninitialized memory.
                     This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
                     The overwriting error message was: Key file does not have group 'spotify'
Sep 23 00:58:19 bubbis spotifile[19071]: No Spotify password specified: Key file does not have group 'spotify'
Sep 23 00:58:19 bubbis spotifile[19071]: Missing Spotify username
```

Trying to login and only return 1 and output to syslog is probably a bad habit
for exiting early, writing the error message to stdout/stderr would be more friendly.

**Comment by catharsis** [comment]
> Readme says "[spotifile]", syslog says "[spotify]"

Yikes! That's just bad, I'll fix that right away, thanks for reporting it! (The section should be called `[spotify]`, since it contains libspotify specific settings.)

> Sep 23 00:58:19 bubbis spotifile[19071]: GError set over the top of a previous GError or uninitialized memory.
>                      This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
>                      The overwriting error message was: Key file does not have group 'spotify'

This is definitely a bug, thanks for reporting it.

> Trying to login and only return 1 and output to syslog is probably a bad habit
> for exiting early, writing the error message to stdout/stderr would be more friendly.

Oh yeah, that's been bugging me as well - I agree we should fix that. It's probably the case that we should do all logging to stderr until we've successfully mounted and initialised.

**Comment by catharsis** [comment]
I've opened #30 and #31 to track the GError bug and startup logging issues, respectively. This issue now tracks the documentation issue, since that's most consistent with the subject.
