### ISSUE TITLE
Streaming quality

### ISSUE THREAD

**Issue by gsora** [catharsis/spotifile#41]
What stream quality is selected when streaming?

**Comment by catharsis** [comment]
The bitrate_preset option sets the preferred bitrate. Unfortunately, I haven't gotten around to document it (#36) yet.

**Comment by catharsis** [comment]
I just pushed 66daa39f08b0, which documents the available configuration options, including bitrate_preset. Thanks for asking!

**Comment by gsora** [comment]
Thank you!
