### ISSUE TITLE
Successfully mounts but not logged in

### ISSUE THREAD

**Issue by ghost** [catharsis/spotifile#49]
This may relate to the new June update depricating libspotify.  It may not.

cat connection yields "logged out"

Idea: Include an error directory or file to log problems.

**Comment by catharsis** [comment]
@x0x7 Mounting does not require logging in. Perhaps a silly question, but, did you supply valid (premium) account details either in your `spotifile.conf` or when mounting?

Log messages are logged to `syslog` if the program is run in the background, and to `stdout` if it is run in the foreground.

Maybe running with the `-f` flag (for foreground) would be helpful. Or `-d` (for debug), if that doesn't help.

**Comment by denysvitali** [comment]
[M @ 2016-06-23 23:50:15 CEST] spotifile: spotify: login failed (Needs a premium account)

In the readme the Premium account requirement wasn't specified.
