### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by ttmx** [catharsis/spotifile#55]
Hey, I know this hasn't been touched in years, any chance of it getting updated at all? Its a very neat project, but currently crashes any time you try to touch the spotify API.

Thanks!

**Comment by catharsis** [comment]
Hi! Sorry, but between work and family, I unfortunately don't really have any time to spend on my side projects right now. My interest in Spotifile waned as a result of Spotify not giving any love to their C bindings, so I haven't really revisited the project at all in recent years.

Though I'm intrigued as to why it's no longer working? Has there been any update to the API? Or maybe they changed something on the server side? Either way, if someone wants to help out with maintenance of the project I'm completely open to discussing the prospect. Just let me know 👍

**Comment by ttmx** [comment]
I have no idea what it could be. I'm sadly not familiar with spotify's API
at all. Would be very cool if you could take a look, but obviously there is
zero obligation to. Thank you a bunch for the project!

**Comment by catharsis** [comment]
Yeah, looks like it's been declared dead at last. A quick search (for libspotify) lead me to https://github.com/mopidy/libspotify-archive/issues/1#issue-335284870. 

Party's over, I'm afraid. I should probably update the README to point that out. 

Thanks for reaching out, regardless 😊

**Comment by ttmx** [comment]
Np!
